### PR TITLE
PWT Movesets + Extras

### PR DESCRIPTION
**Pull request by red031000**
re-opening PR #31

### CODE REVIEW

**Comment by Torq-A** [comment]
Quick question: now that the last season of PBR had options for 1v1 or 2v2 matches, would it make sense to keep the PWT sets which only have two Pokémon for those specific situations?

**Comment by Torq-A** [comment]
Okay, yeah since we can still do 1v1 and 2v2 matches through tokens, you can keep the deleted PWT sets if you integrate this in

**Comment by Torq-A** [comment]
No idea why it's still triggering a compile error in changes_info, but whatever. It's out of my hands now.

**Comment by Torq-A** [comment]
Trying to update this one to remove the end dashes, but for some reason it keeps wanting to merge with the separate runmons update. Will try to edit later when I figure out the issue

**Comment by Felk** [comment]
I'm not sure what you mean by that. I see you have a separate branch for runmons updates, which has its own pull request. What do you want to remove and/or combine exactly?

**Comment by Torq-A** [comment]
No problem. I’ll work more on that this week.

**Comment by Torq-A** [comment]
Yeah this one is a bit old and I tried to repurpose a bunch of these in the branchpruning one. It can be abandoned, and I’ll just take the stuff here and reimplement another time

**Comment by m4-used-rollout** [comment]
Ok, I'll close this.

**Pull request closed without merging**
