### PR TITLE
XG Lugia Buff

### PR DESCRIPTION
**Pull request by SolarisLumos**
Leftovers was removed from Lugia despite it being it's final item for balancing reasons. With all of the recent imbalance in Runmons though, i'd say it's about time we give it Leftovers just to turn it into how it really was.

### CODE REVIEW

**Comment by mathfreak231** [comment]
xref #23 

probably holding off until we get into the juicy stuff like lax incense ray

**Comment by SolarisLumos** [comment]
fair enough, i suppose.

**Comment by mathfreak231** [comment]
Did you mean to merge shiny walrein into this branch? 😳

**Comment by SolarisLumos** [comment]
I guess? I'm still learning Github so i messed something up, i didn't really realize it.

**Comment by SolarisLumos** [comment]
at this point anything in relation to lugia would be part of a greater runmons buff, no real point in leaving this open

**Pull request closed without merging**
