### PR TITLE
Add additional Halloween movesets

### PR DESCRIPTION
**Pull request by Cooper-2**

### CODE REVIEW

**Comment by Torq-A** [comment]
Quick notes: Sonic is okay, but Xmas already has one with Shaymin (which is Werehog here). Same with Bad Omen, which just seems like another Hallowed Stone set.

**Comment by Torq-A** [comment]
Also based on other movesets, you don’t need to adjust rarity for sets if you want them to have equal probability. 1.0 works fine

**Comment by Cooper-2** [comment]
> Quick notes: Sonic is okay, but Xmas already has one with Shaymin (which is Werehog here). Same with Bad Omen, which just seems like another Hallowed Stone set.

Ok, for Sonic I figured that if there's a similar Christmas set than it wouldn't be an issue since those don't get used at the same  time. I did see the Hallowed Stone set *after* I made my own, and they're definitely the same idea, but I like how mine works. I could change it to a Sableye set if that works.

**Comment by Cooper-2** [comment]
> Also based on other movesets, you don’t need to adjust rarity for sets if you want them to have equal probability. 1.0 works fine

Ok, that's good to know!

**Comment by Torq-A** [comment]
> > Quick notes: Sonic is okay, but Xmas already has one with Shaymin (which is Werehog here). Same with Bad Omen, which just seems like another Hallowed Stone set.
> 
> Ok, for Sonic I figured that if there's a similar Christmas set than it wouldn't be an issue since those don't get used at the same time. I did see the Hallowed Stone set _after_ I made my own, and they're definitely the same idea, but I like how mine works. I could change it to a Sableye set if that works.

Yeah okay that’s fair. Whatever works for you I guess

**Comment by Torq-A** [comment]
Ghost Plate is Spooky Plate

**Pull request merged**
