### PR TITLE
The Runmons Reckoning 

### PR DESCRIPTION
**Pull request by SolarisLumos**
You asked me to move the files. So i did. Let me know if i still managed to screw up. I'd also be happy to explain these runmons changes again if needed.

(Yes this is another new repository. I don't know why this has become a habit but i had many things to fix and didn't wanna spam commits lol)

### CODE REVIEW

**Comment by Felk** [comment]
Haha, you don't need to re-create the entire repository for that. You can just make a new branch within the same repository, or even rewrite the history of the current branch if you're really comfortable with git.

Anyway, I see that you accidentally changed the line endings from LF/Linux (as is usually the standard for files in git) to CRLF/Windows. This makes the diff look like you removed and re-added each line, which can be annoying.

What tool do you use to upload or change the files? Apparently it has silly default settings, causing issues like these.

**Comment by SolarisLumos** [comment]
I use Atom. I was not aware it did this. What text editor would you recommend?

**Comment by Felk** [comment]
atom is probably fine. I committed a `.gitattributes` file to the master branch, maybe that will be enough for atom to commit the files correctly. please try to merge the newest master into your branch and commit the files again (add a newline or something if they don't show up as changed, so you can commit them)

**Comment by Torq-A** [comment]
I was just curious - does Sword have any Runmons? If I’m not mistaken, that’s the only game still left which hasn’t been added to the Runmons list yet.

**Comment by SolarisLumos** [comment]
> atom is probably fine. I committed a `.gitattributes` file to the master branch, maybe that will be enough for atom to commit the files correctly. please try to merge the newest master into your branch and commit the files again (add a newline or something if they don't show up as changed, so you can commit them)

So this is going to sound like a dumb question, but my familiarity with this site is little considering i've only ever had to just commit files. How do you actually...merge a branch, exactly? The tutorials i'm finding online don't seem like they're helpful in this instance, unless i'm blatantly misunderstanding something.

**Comment by Felk** [comment]
Ah, that's alright, I'll do it for you

**Comment by Felk** [comment]
All you need to do now is to git pull before doing any additional changes, so atom sees the `.gitattributes` files I added.

**Comment by SolarisLumos** [comment]
Thanks for the help! Sorry for any trouble i caused you, i'll be looking more in-depth into Github/Git tutorials later so i can navigate my way around better.

**Comment by SolarisLumos** [comment]
> I was just curious - does Sword have any Runmons? If I’m not mistaken, that’s the only game still left which hasn’t been added to the Runmons list yet.

M4 refuses to give me the safe, so there isn't really anything i can do.

**Comment by Felk** [comment]
> Thanks for the help! Sorry for any trouble i caused you, i'll be looking more in-depth into Github/Git tutorials later so i can navigate my way around better.

You're not at fault. People really shouldn't have to deal with line ending issues in 2021 but yet here we are. I'll gladly do the plumbing for people so they don't have to deal with it

**Comment by Felk** [comment]
@SolarisLumos is it okay if I merge the master branch into this one to check if the automatic workflows I added are working? you'll have to "git pull" once I do that to get up-to-date

**Comment by Felk** [comment]
well that didn't work, but here is what it would have posted:

Stats:

| file | set | hp | atk | def | spe | spA | spD |
| --- | --- | --- | --- | --- | --- | --- | --- |
| pokesets/1 XM_Standard/XM_Bronzong.yaml | Christmas | 262 | 183 | 237 | 181 | 163 | 241 |
| pokesets/1 XM_Standard/XM_Bronzong.yaml | Christmas3 | 244 | 164 | 237 | 102 | 282 | 237 |
| pokesets/1 XM_Standard/XM_Crobat.yaml | Christmas | 280 | 210 | 165 | 265 | 205 | 165 |
| pokesets/1 XM_Standard/XM_Heracross.yaml | Christmas | 301 | 301 | 186 | 206 | 116 | 226 |
| pokesets/1 XM_Standard/XM_Kabutops.yaml | Christmas2 | 261 | 266 | 246 | 259 | 198 | 176 |
| pokesets/1 XM_Standard/XM_Mantine.yaml | Christmas | 271 | 179 | 176 | 176 | 259 | 316 |
| pokesets/1 XM_Standard/XM_Mothim.yaml | Christmas | 306 | 201 | 161 | 183 | 262 | 161 |
| pokesets/1 XM_Standard/XM_Vespiquen.yaml | Christmas | 250 | 221 | 209 | 127 | 148 | 209 |
| pokesets/1 XM_Standard/XM_Wigglytuff.yaml | Christmas2 | 390 | 176 | 115 | 126 | 186 | 125 |
| pokesets/1 XM_Standard/XM_Wigglytuff.yaml | Christmas3 | 390 | 239 | 126 | 126 | 155 | 136 |
| pokesets/Runmon/09_X.yaml | TPP X | 267 | 353 | 158 | 193 | 203 | 123 |
| pokesets/Runmon/09_X.yaml | TPP X | 309 | 255 | 201 | 236 | 221 | 206 |
| pokesets/Runmon/09_X.yaml | TPP X | 350 | 279 | 213 | 244 | 203 | 191 |
| pokesets/Runmon/09_X.yaml | TPP X | 413 | 227 | 200 | 181 | 213 | 227 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 333 | 151 | 211 | 133 | 163 | 201 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 350 | 242 | 149 | 177 | 214 | 139 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 302 | 270 | 193 | 287 | 284 | 257 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 313 | 186 | 133 | 261 | 157 | 150 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 289 | 188 | 162 | 258 | 246 | 122 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 274 | 124 | 168 | 251 | 206 | 188 |
| pokesets/Runmon/10_OmegaRuby.yaml | TPP Omega Ruby | 336 | 380 | 228 | 228 | 315 | 256 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 264 | 294 | 139 | 166 | 245 | 245 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 200 | 94 | 76 | 240 | 260 | 260 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 220 | 88 | 143 | 97 | 83 | 83 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 162 | 41 | 121 | 169 | 62 | 62 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 207 | 118 | 163 | 199 | 220 | 245 |
| pokesets/Runmon/11_AnniversaryRed.yaml | TPP Anniversary Red | 274 | 182 | 163 | 268 | 165 | 165 |
| pokesets/Runmon/12_PuppetPlay.yaml | TPP Puppet Play | 250 | 236 | 172 | 237 | 131 | 193 |
| pokesets/Runmon/17_Brown.yaml | TPP Brown | 207 | 192 | 133 | 267 | 129 | 169 |
| pokesets/Runmon/20_Sun.yaml | TPP Sun | 275 | 219 | 177 | 138 | 150 | 185 |
| pokesets/Runmon/20_Sun.yaml | TPP Sun | 259 | 136 | 110 | 155 | 175 | 159 |
| pokesets/Runmon/20_Sun.yaml | TPP Sun | 257 | 241 | 180 | 232 | 140 | 154 |
| pokesets/Runmon/20_Sun.yaml | TPP Sun | 206 | 132 | 112 | 181 | 88 | 113 |
| pokesets/Runmon/20_Sun.yaml | TPP Sun | 261 | 231 | 170 | 243 | 137 | 179 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 309 | 236 | 213 | 167 | 245 | 240 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 306 | 297 | 173 | 206 | 173 | 248 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 346 | 327 | 232 | 300 | 189 | 196 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 281 | 177 | 146 | 273 | 156 | 156 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 347 | 223 | 221 | 257 | 271 | 223 |
| pokesets/Runmon/32_FloraSky.yaml | TPP Flora Sky | 1 | 226 | 143 | 136 | 95 | 106 |
| pokesets/Runmon/33_FusedCrystal.yaml | TPP Fused Crystal | 223 | 135 | 120 | 231 | 102 | 102 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 264 | 171 | 125 | 159 | 99 | 151 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 642 | 72 | 79 | 159 | 188 | 267 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 298 | 207 | 195 | 251 | 246 | 211 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 340 | 261 | 224 | 229 | 162 | 236 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 232 | 269 | 145 | 212 | 89 | 257 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 308 | 162 | 201 | 218 | 167 | 163 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 258 | 194 | 186 | 282 | 264 | 210 |
| pokesets/Runmon/34_BurningFireRed.yaml | TPP Burning FireRed | 283 | 177 | 201 | 136 | 223 | 182 |
| pokesets/Runmon/34_BurningRed.yaml | TPP Burning Red | 312 | 196 | 184 | 229 | 247 | 199 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 281 | 259 | 166 | 138 | 273 | 149 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 259 | 151 | 168 | 159 | 131 | 204 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 229 | 203 | 196 | 123 | 157 | 176 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 301 | 194 | 202 | 174 | 191 | 268 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 368 | 246 | 186 | 136 | 167 | 164 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 293 | 285 | 396 | 141 | 157 | 150 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 262 | 165 | 288 | 163 | 106 | 169 |
| pokesets/Runmon/43_GauntletEmerald.yaml | TPP Gauntlet Emerald | 321 | 320 | 176 | 219 | 216 | 220 |
| pokesets/Runmon/45_GauntletBlazeBlack2.yaml | TPP Gauntlet Black 2 | 314 | 185 | 190 | 234 | 260 | 278 |
| pokesets/Runmon/45_GauntletBlazeBlack2.yaml | TPP Gauntlet Black 2 | 306 | 213 | 145 | 261 | 306 | 194 |
| pokesets/Runmon/45_GauntletBlazeBlack2.yaml | TPP Gauntlet Black 2 | 268 | 244 | 224 | 298 | 316 | 211 |
| pokesets/Runmon/45_GauntletBlazeBlack2.yaml | TPP Gauntlet Black 2 | 237 | 232 | 290 | 120 | 177 | 295 |
| pokesets/Runmon/47_Sirius.yaml | TPP Sirius | 269 | 318 | 209 | 204 | 153 | 142 |
| pokesets/Runmon/47_Sirius.yaml | TPP Sirius | 320 | 364 | 294 | 194 | 198 | 194 |
| pokesets/Runmon/47_Sirius.yaml | TPP Sirius | 269 | 184 | 157 | 226 | 222 | 180 |
| pokesets/Runmon/48_Rising Ruby.yaml | TPP Rising Ruby | 1 | 203 | 141 | 104 | 85 | 96 |
| pokesets/Runmon/49_Vega.yaml | TPP Vega | 161 | 114 | 184 | 86 | 94 | 207 |
| pokesets/Runmon/TrickOrTreatHouse.yaml | TPP Trick House | 151 | 26 | 489 | 42 | 50 | 520 |

**Comment by Felk** [comment]
sorry for abusing your pull request for this, but I needed an actual external fork from someone without write access to test this, and now it _finally_ works.

**Review by Torq-A — CHANGES_REQUESTED** [review]
A few errors according to the compile check that was made:

XM_Duskull is both hidden and biddable. Can only be one or the other. 
XM_Kabutops and XM_Mantine have Water Gun in two slots. 
The Shedinja from Rising Ruby must be genderless.

**Comment by red031000** [comment]
merging since this is a continuation from a PR from december 2020

**Review by red031000 — APPROVED** [review]

**Pull request merged**
