### PR TITLE
Adding PMD Randomized Sky runmons

### PR DESCRIPTION
**Pull request by rjri**
movesets and abilities are correct, need changes in natures, ivs and evs for balance (these don't exist in PMD)

### CODE REVIEW

**Comment by mathfreak231** [comment]
I disagree with adding the NPC pokemon. The focus of Runmons is to highlight pokemon that TPP itself ~~caught~~ recruited and raised.

I'll look into stats when I get the chance, or someone else can.

**Comment by rjri** [comment]
I added those because they were the playable pokemon in Special Episode 5, which TPP played and finished, though I guess they were technically not part of TPP's main team.

**Comment by red031000** [comment]
bump?

**Comment by mathfreak231** [comment]
Apparently I'm in the minority for not wanting the SE5 ones, meh. Guess it's fine

**Pull request merged**
